'use client'

import Head from 'next/head';
import '../globals.scss';


/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (<>
            <Head>
                <title>Vylety</title>
            </Head>
            <main className={`m-5`}>

                {children}
            </main>
        </>
    );
}
